// data.js — content extracted from Ikarmic-Website codebase.
// Loaded as a plain script (window globals) so Babel components can read it.

window.IK_DATA = {
  tickerItems: [
    "AI Chatbots & Conversational AI",
    "Demand Forecasting",
    "Generative AI",
    "Predictive Analytics",
    "Custom ML Models",
    "Business Automation",
    "RAG Pipelines",
    "LLM Fine-Tuning",
    "Computer Vision",
    "Data Engineering",
    "MLOps & Monitoring",
    "Responsible AI",
  ],
  miniStats: [
    { v: "50+", l: "AI Projects" },
    { v: "4", l: "Industries" },
    { v: "6 wks", l: "POC to Prod" },
    { v: "2-day", l: "Response SLA" },
  ],
  stats: [
    { value: "50+", label: "AI Projects Delivered", sub: "across 4 industries" },
    { value: "65%", label: "Avg. Ticket Deflection", sub: "for chatbot deployments" },
    { value: "6 wks", label: "POC to Production", sub: "median delivery time" },
    { value: "100%", label: "IP Ownership", sub: "always transferred to you" },
  ],
  services: [
    {
      num: "01",
      title: "AI Chatbots & Conversational AI",
      desc: "Intelligent chatbots across web, WhatsApp, and messaging platforms — resolving tier-1 and tier-2 queries 24/7 without adding headcount.",
      featured: true,
      tint: "indigo",
      badge: "Most Popular",
      iconPath: "M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z",
    },
    {
      num: "02",
      title: "Business Automation",
      desc: "Automate repetitive workflows, document processing, and operations to cut costs and free your team for high-value work.",
      tint: "violet",
      iconPath: "M13 10V3L4 14h7v7l9-11h-7z",
    },
    {
      num: "03",
      title: "Data Analytics & Predictive AI",
      desc: "Turn raw data into strategic decisions — forecasting outcomes, detecting risk, and optimising margins at scale.",
      tint: "blue",
      iconPath: "M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z",
    },
    {
      num: "04",
      title: "Generative AI Solutions",
      desc: "Production-grade LLM systems — RAG pipelines, fine-tuned models, guardrails — that create real content and real leverage.",
      tint: "emerald",
      iconPath: "M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z",
    },
    {
      num: "05",
      title: "Custom AI Development",
      desc: "Bespoke models designed for your specific problem — from prototype to production with full IP transfer and team enablement.",
      tint: "orange",
      iconPath: "M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4",
    },
  ],
  testimonials: [
    {
      quote: "Our customer support ticket volume dropped 62% in the first month. The chatbot handles what used to take 8 agents, and CSAT actually went up.",
      name: "Priya R.",
      title: "Head of Customer Experience",
      company: "Retail Brand",
      avatar: "PR",
      color: "linear-gradient(135deg, #6366f1, #a78bfa)",
    },
    {
      quote: "The demand forecasting model paid for itself within three weeks. We cut overstock losses by ₹40L in Q1 alone. The ROI case was immediate.",
      name: "Ankit M.",
      title: "VP Operations",
      company: "Manufacturing Group",
      avatar: "AM",
      color: "linear-gradient(135deg, #10b981, #14b8a6)",
    },
    {
      quote: "Ikarmic moved at a pace we'd never seen from an AI vendor. POC in week two, production in week six, full IP handover on day forty.",
      name: "Sarah L.",
      title: "CTO",
      company: "EdTech Startup",
      avatar: "SL",
      color: "linear-gradient(135deg, #f97316, #f43f5e)",
    },
  ],
  blogPosts: [
    {
      tag: "STRATEGY",
      tagTint: "indigo",
      readTime: "7 min",
      date: "19 Apr 2026",
      title: "Why Adaptive AI Systems Outperform Static Models",
      excerpt: "Static models decay. Markets shift, data drifts. Here's how Ikarmic's adaptive systems keep AI accurate long after launch.",
    },
    {
      tag: "GOVERNANCE",
      tagTint: "violet",
      readTime: "5 min",
      date: "19 Apr 2026",
      title: "Ethical by Design: AI Governance Can't Be a Checklist",
      excerpt: "Compliance isn't a finish line — it's a baseline. Ikarmic builds bias checks and privacy guardrails into every system from day one.",
    },
    {
      tag: "PRODUCT",
      tagTint: "emerald",
      readTime: "6 min",
      date: "19 Apr 2026",
      title: "The Invisible AI: Human-Centered Design Meets ML",
      excerpt: "The best AI doesn't announce itself. It surfaces the right answer, explains its confidence, and hands control back to the user.",
    },
  ],
  steps: [
    { num: "01", title: "Discovery", duration: "Week 1", desc: "A focused 3-day working session to map your data, systems, and goals — no slide decks, all real work." },
    { num: "02", title: "Design & Build", duration: "Weeks 2–5", desc: "Rapid sprints with weekly working demos. You see real models running against your data before each sprint ends." },
    { num: "03", title: "Deploy & Scale", duration: "Week 6+", desc: "Production-grade deployment with monitoring, retraining schedules, and full team enablement — then we step back." },
  ],
  navServices: [
    { label: "AI Chatbots", desc: "24/7 support, no extra headcount", iconPath: "M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z" },
    { label: "Business Automation", desc: "Eliminate repetitive manual work", iconPath: "M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" },
    { label: "Data Analytics", desc: "Surface insights from your data", iconPath: "M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10" },
    { label: "Generative AI", desc: "Content and code at scale", iconPath: "M13 10V3L4 14h7v7l9-11h-7z" },
  ],
};
